In [2]:
import numpy as np
from ldpc import BpOsdDecoder
import time

In [5]:
path = 'pcm.txt'
file = open(path, 'r')
data = file.readlines()
ns = 132
nq = 288
H = np.zeros((ns, nq),dtype=np.uint8)
for k in range(len(data)):
    H[k,:] = np.array(data[k].split(),dtype=np.uint8)
print(H)

[[0 1 1 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 1]
 [0 0 0 ... 0 0 1]]


In [8]:
path = 'error.txt'
file = open(path, 'r')
data = file.readlines()
time_sum = 0
bp_osd = BpOsdDecoder(
            H,
            error_rate = 0.01,
            bp_method = 'product_sum',
            max_iter = 7,
            schedule = 'serial',
            osd_method = 'OSD_0', #set to OSD_0 for fast solve
            osd_order = 0
        )
for i in range(len(data)):
    e = np.array(data[i].split(),dtype=np.uint8)
    start_time = time.time()
    decoding = bp_osd.decode(H.dot(e))
    end_time = time.time()
    time_sum += end_time - start_time
print(time_sum/len(data))

1.9775376319885253e-05
